name: messenger
description: A messenger application inspired by Telegram with Express.js backend and WebSockets
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.5.3

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    socket_io_client: ^2.0.3+1
    http: ^1.2.0
    shared_preferences: ^2.2.2
    provider: ^6.1.1
    intl: ^0.19.0
    file_picker: ^8.1.2
    image_picker: ^1.0.7
    cached_network_image: ^3.3.1
    flutter_local_notifications: ^17.2.2
    encrypt: ^5.0.3
    path_provider: ^2.1.2
    jwt_decoder: ^2.0.1
    flutter_secure_storage: ^9.0.0

dev_dependencies:
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/

    fonts:
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Regular.ttf
              - asset: assets/fonts/Roboto-Bold.ttf
                weight: 700
